### ISSUE TITLE
Store sfdir in git repository

### ISSUE THREAD

**Issue by tuffnatty** [typiconman/fonts-cu#15]
I think that storing the font as separate glyph files in a .sfdir instead of a single huge .sfd file would be much better for tracking revision history and for clean git merging (if you are going to accept 3rd party contributions).

**Comment by typiconman** [comment]
That sounds like a good idea.

**Comment by starover77** [comment]
It seems like a good idea, but I tend to think that it will be incredibly confusing and cumbersome to have a separate file for every single glyph in the font, especially considering that I am currently adding about 300-400 new Slavonic glyphs in the PUA. (These new additions represent the fullness of the Ustav and Poluustav handwriting traditions and conventions -- a series of subtle features and character nuances which have been largely undocumented and undiscussed in recent centuries.)

**Comment by tuffnatty** [comment]
I meant the standard sfdir format of FontForge. You'll notice almost no difference from FontForge user perspective.

**Comment by KrasnayaPloshchad** [comment]
I think remake some characters by insert glyph reference(s) is enough, it would also reduce size of source code, also would generate lighter font file.

**Comment by typiconman** [comment]
@KrasnayaPloshchad :+1:

**Comment by typiconman** [comment]
@tuffnatty: One of the problems is the fact that some of the scripts we use to build fonts rely on the SFD format. For example, sfd2ap. We would have to rewrite the build sequence.

**Comment by typiconman** [comment]
Actually, I am thinking about converting to UFO format:
http://unifiedfontobject.org/
It is supported by FontForge, but seems to be a better idea in the long run in terms of storage. It will also allow us to interact with other font design applications.

@starover77 and others, please comment on this proposal.

**Comment by starover77** [comment]
It seems to have potential, but my life is too busy right now for me to take on learning another coding project. After glancing over the UFO project, I did notice that there is the possibility of color designation, which would be greatly beneficial for use with neumatic musical notations. If you can figure this system out and make it work for us, and then present it to us in an easy-to-understand format, I'm perfectly willing to work with it.

(PS: I recently got a promotion at work as the store supervisor, and I've got a lot to learn during the winter season to prepare for the summer season. I also have to move by May 1st, and I'm trying to find a new place to live, which means another life disruption. When I moved home to Maine last spring, I knew it would take some time for me to get fully settled, and it seems that the process is not over yet.)

**Comment by typiconman** [comment]
Since there seems to be no interest among the developers to support this, I am closing the issue.
