### ISSUE TITLE
Menaion Unicode: extraneous Diacritic Mark anchor in uni00CB

### ISSUE THREAD

**Issue by tuffnatty** [typiconman/fonts-cu#16]
As per title

**Comment by typiconman** [comment]
I don't think it's extraneous, I think it's just mispositioned. A user could, in principle, want to place another diacritical mark on top U+00CB. It would just need to stack above the diaeresis.

**Comment by tuffnatty** [comment]
it is a MARK anchor, not a BASE anchor

**Comment by typiconman** [comment]
Oh, OK. I will fix it. Thanks.

**Comment by typiconman** [comment]
Fixed.
