### ISSUE TITLE
Ponomar Unicode: Big Yus has bad hinting

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [typiconman/fonts-cu#17]
I found Big Yus has bad hinting in Ponomar Unicode on [this page](http://www.ponomar.net/files/gama2/p010.htm), when I enlarge in bigger size the problem seems disappeared. But when I resize in 100% it was appearing again.
![default](https://cloud.githubusercontent.com/assets/10364351/19382957/f8460e18-9234-11e6-81c2-8615b6b21b9b.PNG)

**Comment by starover77** [comment]
I am puzzled. I am not having any problems with hinting on my computer, zooming in and out. I am using Linux Mint 18.

**Comment by KrasnayaPloshchad** [comment]
OK it was disappeared when I delete a OTF version of the font, which is generated by myself 6 months ago when I try to test new design of У, it’s no problem for me. BTW I think the right curly bracket on this page can be redesigned using [Miscellaneous Technical](https://graphemica.com/blocks/miscellaneous-technical) characters.
```
<span style="display:inline-block;vertical-align:middle;line-height:1em;">
<span style="display:block">⎫</span>
<span style="display:block">⎬</span>
<span style="display:block">⎭</span>
</span>
```

**Comment by typiconman** [comment]
Thanks, I implemented your suggestion for the bracket. It looks much better!
