### ISSUE TITLE
Ponomar Unicode: Combining Cyrillic Thousand Millions Sign has wrong positioning to ы

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [typiconman/fonts-cu#19]
On [Изображение славянских чисел](http://www.ponomar.net/files/gama2/p005.htm) I found Combining Cyrillic Thousand Millions Sign does not work with ы in Ponomar Unicode.

**Comment by typiconman** [comment]
It's a bug.

**Comment by typiconman** [comment]
I believe that this is now fixed.
We have resolved a number of bugs in the last few months, updated the PUA Policy (see here: http://www.ponomar.net/files/pua_policy.pdf), and added a new font (Monomakh), so I think it is time for a release.
@KrasnayaPloshchad @starover77, and others please take a look and make sure there are no problems. If there are no problems, I will formally release all of the fonts.
For convenience, I posted all of the font files as one archive here:
http://www.ponomar.net/files/fonts-churchslavonic.zip

**Comment by KrasnayaPloshchad** [comment]
OK, they are good.

**Comment by KrasnayaPloshchad** [comment]
Also, in font-churchslavonic.pdf section 7.3.3, OpenType does not have `loca` feature tag, instead is `locl`.

**Comment by typiconman** [comment]
Fixed with e8c7c22f4903a8de6f87008f661fd6558e604f71.
