### ISSUE TITLE
MonomakhUnicode font badly broken on print media

### ISSUE THREAD

**Issue by pgmmpk** [typiconman/fonts-cu#21]
PDF created with MonomakhUnicode looks good on computer, but when printing glyphs come out 2x larger than they should.

This problem does not happen with PonomarUnicode font. Nor does it happen with the original Monomachus font.

Here is the broken PDF: 
[epiphany-ru.MonomakhUnicode.pdf](https://github.com/typiconman/fonts-cu/files/706040/epiphany-ru.MonomakhUnicode.pdf)

It prints like this:
![img_20170114_111646](https://cloud.githubusercontent.com/assets/569458/21956273/5354cdfe-da4b-11e6-8b6b-50881f4c1e14.jpg)

Here is same text typeset with Monomachus (and it prints fine):
[epiphany-ru.Monomachus.pdf](https://github.com/typiconman/fonts-cu/files/706041/epiphany-ru.Monomachus.pdf)

This one prints nicely:
![img_20170114_111656](https://cloud.githubusercontent.com/assets/569458/21956279/603ec5ce-da4b-11e6-8a52-d4d57afe068d.jpg)

**Comment by typiconman** [comment]
That's very weird. Right now I don't have a printer to try to reproduce the problem. Maybe it's an issue with the OS/2 table ...

**Comment by pgmmpk** [comment]
If you have an idea how to troubleshoot it further, I can try doing it over here. Is not PDF supposed to look same on any media? Weird indeed...

**Comment by typiconman** [comment]
Does the same problem occur both in the OpenType and TrueType versions of the font?

**Comment by pgmmpk** [comment]
Yes, in both

**Comment by pgmmpk** [comment]
<img width="775" alt="screen shot 2017-01-14 at 1 25 43 pm" src="https://cloud.githubusercontent.com/assets/569458/21957084/4b3f1d60-da5d-11e6-865d-2f0410b8a81c.png">

<img width="770" alt="screen shot 2017-01-14 at 1 26 39 pm" src="https://cloud.githubusercontent.com/assets/569458/21957087/53f3a174-da5d-11e6-8715-7de1328e67a1.png">

**Comment by pgmmpk** [comment]
This is unrelated, but FontForge gives the following warning when opening MonomakhUnicode:

![image](https://cloud.githubusercontent.com/assets/569458/21957100/9ee273b8-da5d-11e6-809f-46bfd8fe5c84.png)

**Comment by typiconman** [comment]
Looks like the metrics in the OS/2 table got almost doubled. Maybe that is why the problem is occurring? Can you try the attached file?

**Comment by pgmmpk** [comment]
Please, post the attachment

**Comment by typiconman** [comment]
Sorry, GitHub won't let me attach. Try here:
http://www.ponomar.net/files/MonomakhUnicode.zip

**Comment by pgmmpk** [comment]
No luck - still prints Huge letters. 

Additionally, now glyphs in FontForge look much bigger.

I noticed that in the General tab Em Size is much bigger than in the original...

<img width="783" alt="screen shot 2017-01-14 at 1 48 19 pm" src="https://cloud.githubusercontent.com/assets/569458/21957249/8397baac-da60-11e6-9733-de3694dd6727.png">

<img width="785" alt="screen shot 2017-01-14 at 1 49 13 pm" src="https://cloud.githubusercontent.com/assets/569458/21957245/7434b27c-da60-11e6-9cf1-135bc1a23d1c.png">

**Comment by pgmmpk** [comment]
Aleksander,

you are on the right track. I did some changes (not really understanding what I am doing) and
now it looks and prints correctly.

I think I did this:

1. In the OS/2 Metrics tab I also changed X height and Capital Height values to match Monomachus
2. In the General I switched to 1000 Em Size (because font export gave me warning).

**Comment by typiconman** [comment]
I was not able to reproduce your error: your file epiphany-ru.MonomakhUnicode.pdf prints just fine (using Adobe Reader on Windows XP). What platform are you using?

That said, I will change the metrics in MonomakhUnicode to match the metrics in Monomachus. I probably won't get around to it until tomorrow, though.

**Comment by pgmmpk** [comment]
Double-checked the PDF file. Yes, reproduces here. 

macOS Sierra 10.12.2, printing from default "Preview" application or from Chrome built-in PDF viewer

Printer: Brother MFC 7460DN

Installed Acrobat Reader. From there prints incorrectly - broken even worse:

![img_20170115_152952](https://cloud.githubusercontent.com/assets/569458/21965951/cd726b7c-db37-11e6-8dfb-c4fa103211af.jpg)

**Comment by typiconman** [comment]
I am confused as to what is going on. When I open the version of the Monomachus font that is stored in the repository here:
https://github.com/akryukov/monomachus
I see the same metrics, as in Monomakh Unicode:
![screenshot from 2017-01-16 19 29 58](https://cloud.githubusercontent.com/assets/5428695/21991116/c9507ee6-dc2a-11e6-9ce3-5ee63092e9ee.png)

![screenshot from 2017-01-16 19 32 22](https://cloud.githubusercontent.com/assets/5428695/21991155/ea6fb3d0-dc2a-11e6-92fd-de0aae003879.png)

Can you confirm that the metrics are the same (or different) when you open Monomachus in FontForge on Mac OS X? Perhaps this is a problem specific to OS X?

**Comment by pgmmpk** [comment]
Curiouser and curiouser...

Loaded Monomachus.sfd into FF on Mac:
<img width="625" alt="screen shot 2017-01-16 at 7 01 02 pm" src="https://cloud.githubusercontent.com/assets/569458/22003011/7272d224-dc1e-11e6-8ead-1a6e32f68d3e.png">

<img width="782" alt="screen shot 2017-01-16 at 7 01 35 pm" src="https://cloud.githubusercontent.com/assets/569458/22003018/7ac90d9e-dc1e-11e6-81bb-8d34f64a186b.png">

**Comment by pgmmpk** [comment]
Eureka!

Contents of `monomachus-generate.py` in monomachus directory is below.
Things to notice:

1. SFD file is used to generate WOFF file (as-is). On top of this:
2. For OTF and TTF `encoding` is set to "mac"
3. For OTF "em" is set to 1000
```
import fontforge

base_name = "Monomachus"
fontrev = 1.0

def process_font(name):
    filename = name
    font = fontforge.open(filename + ".sfd")

    woff_meta = name + "-WOFF-metadata.xml"
    f = file( woff_meta,'r' )
    lines = f.readlines()
    f.close()
    font.version = str( fontrev )
    font.sfntRevision = fontrev
    font.woffMetadata = "".join( lines )
    font.generate( filename + ".woff",layer="TTF" )

    font.encoding = "mac"
    font.generate(filename + ".ttf",flags=("opentype","old-kern","PfEd-colors","PfEd-lookups","dummy-dsig"),layer="TTF")

    font.em = 1000
    font.generate(filename + ".otf",flags=("opentype","PfEd-colors","PfEd-lookups"),layer="Fore")
    font.close()

process_font( base_name )
```

**Comment by typiconman** [comment]
Can you try with the file that I e-mailed you? I changed the em-size to 1000 for the OTF and 1024 for the TTF.

**Comment by pgmmpk** [comment]
All fixed. Tried MacOs' "Preview" and "AcrobatRerader". Both print nicely.

See snapshots below. Thank you for fixing this!

Acrobat:
![img_20170117_112828](https://cloud.githubusercontent.com/assets/569458/22029346/3e71211c-dca8-11e6-92cc-f077f8b0f31e.jpg)

Preview:
![img_20170117_112801](https://cloud.githubusercontent.com/assets/569458/22029347/3e74c948-dca8-11e6-8618-3c0a20750a07.jpg)

**Comment by pgmmpk** [comment]
Forgot to mention: the above experiment was for OTF fonts. 

TTF versions also print cleanly and nicely.

**Comment by typiconman** [comment]
Sorry, I referenced the wrong issue.

I believe that *this* issue is now fixed. Please test, and let me know if there are any further problems.

**Comment by typiconman** [comment]
@pgmmpk Question: is there a way to automatically update the website once the fonts are built in the fonts repository?

**Comment by pgmmpk** [comment]
No, I do not know how to auto-update sci website. Lets do it manually for now, until it gets too annoying...

Yes, I believe issue is fixed. Please, update the repo and release a fixed version of fonts. Closing the issue
