### ISSUE TITLE
Ponomar: Stylish alternates seems not work with Firefox

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [typiconman/fonts-cu#23]
I have used the same code to test Edge and Firefox, then I found the problem.
```
<p style="font-family: Ponomar Unicode TT; font-size:2em; font-feature-settings: 'salt' 1">У</p>
<p style="font-family: Ponomar Unicode TT; font-size:2em;">
<span style="font-feature-settings: 'salt' 1">🕅</span>
<span style="font-feature-settings: 'salt' 2">🕅</span>
<span style="font-feature-settings: 'salt' 3">🕅</span>
<span style="font-feature-settings: 'salt' 4">🕅</span>
</p>
```
![1](https://cloud.githubusercontent.com/assets/10364351/22209494/abf4e232-e1c1-11e6-911a-38515182f1bc.PNG)
![2](https://cloud.githubusercontent.com/assets/10364351/22209472/911e408e-e1c1-11e6-9df1-7850ca3ab37c.PNG)

**Comment by typiconman** [comment]
Are you sure this is not a problem with the browser?

**Comment by KrasnayaPloshchad** [comment]
I have tested again with both OTF and TTF version of the font, and tested with Chrome 55.0 and LibreOffice 5.3.0.2, then I’m clear what’s wrong with me.
 
On Firefox 51.0 and LibreOffice 5.3.0.2, when I try TTF font, `ss02` and `salt` features failed even if I indicate Church Slavonic language, but on Edge and Chrome 55.0 everything works.
When I try to use OTF font, everything works with me, but I have to indicate Church Slavonic to the text.

Note: LibreOffice got support for OpenType font feature since 5.3, using a syntex previously only supported for Graphite fonts, with this syntex I can get the similar result as I have seen on Firefox.

**Comment by typiconman** [comment]
Can we say then, that this is a problem with the software and not with the font? I think browsers do not completely support optional features such as `salt`.

**Comment by KrasnayaPloshchad** [comment]
Since `salt` and `ss02` features performanced the same on Firefox and LibreOffice 5.3, I think this is a bug in those softwares that cause the conflict between Graphite and OpenType layout.

**Comment by typiconman** [comment]
The Graphite features are only available in the TT font. If you are working with the OTF font, you only have the OpenType features.

**Comment by KrasnayaPloshchad** [comment]
I know what’s wrong with Ponomar Unicode TT. Recently I found LO has a bug related to this problem in their Bugzilla. 
https://bugs.documentfoundation.org/show_bug.cgi?id=105516
According to their developer Graphite or AAT layout would become number one priority then OpenType when a font has related tables.

**Comment by typiconman** [comment]
As the comment on that bug report says, 

> [t]he Graphite layout is used and it is not reasonable to expect OpenType layout to work at the same time. If you don’t want Graphite layout, don’t use graphite fonts.
