### ISSUE TITLE
Monomakh Unicode TT: all splines garbled under Windows 10

### ISSUE THREAD

**Issue by tuffnatty** [typiconman/fonts-cu#24]
It works well for me in XP, 7, and OS X, but after installing under Windows 10 all splines looked awful; sadly I had no chance to make a screenshot. The .otf version worked well.

**Comment by typiconman** [comment]
I cannot test this, as I have no access to Windows 10.

**Comment by KrasnayaPloshchad** [comment]
@typiconman You can get a VM from here if you want to access Windows 10:
https://dev.windows.com/zh-cn/microsoft-edge/tools/vms/

**Comment by KrasnayaPloshchad** [comment]
Microsoft also published Windows 10 VM at Windows Dev Center:
https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

**Comment by KrasnayaPloshchad** [comment]
Alternatively, you can get ISO package from here, than install it into VBox:
https://www.microsoft.com/en-us/software-download/windows10ISO

**Comment by typiconman** [comment]
I'll try to look into this soon. Right now I'm working on fixing the keyboard drivers and updating the documentation.

**Comment by typiconman** [comment]
I have been able to confirm the issue.
![VirtualBox_MSEdge - Win10_17_03_2019_13_08_48](https://user-images.githubusercontent.com/5428695/54488701-19773000-48b6-11e9-90bf-0b89f138edf3.png)

**Comment by typiconman** [comment]
In light of #46 this may be irrelevant.

**Comment by typiconman** [comment]
Closed, since TTF fonts are no longer supported.
