### ISSUE TITLE
PonomarUnicode: некорректное отображение макрона над ѱї в составе сложных титл.

### ISSUE THREAD

**Issue by MakGreg** [typiconman/fonts-cu#26]
Здравствуйте!
При использовании сложного титла, включающего в себя на обоих концах оного символы Combining Cyrillic Titlo Left Half (U+FE2E) и Combining Cyrillic Titlo Right Half (U+FE2F) соответственно, к каждому из которых примыкает символ Combining Conjoining Macron (U+FE26), соединения указанных двух макронов между собою не происходит, аще первый макрон поставлен над Cyrillic Small Letter Psi (U+0471), остальные буквы при сём также являются минускульными.
Прилагаю изображение.
![img_2203](https://cloud.githubusercontent.com/assets/3963468/25026717/980168ee-20b0-11e7-98a7-cbe296dc9ca0.PNG)
[҂и︮ѱ︦к︦д︯]

**Comment by KrasnayaPloshchad** [comment]
I also tested Ponomar Unicode TT on LibreOffice 5.3, works for me. I suggest Combining Conjoining Macron should be longer, or adding some contextual alternetes for it. Also, its position should be adjusted.

![default](https://cloud.githubusercontent.com/assets/10364351/25035433/41740494-2120-11e7-98e1-c1b97b1684d4.PNG)

**Comment by MakGreg** [comment]
Эта проблема возникает и в других случаях.
![img_2208](https://cloud.githubusercontent.com/assets/3963468/25040144/49880ff0-2110-11e7-9e25-7e495b1c9fe7.PNG)
[а︮б︦ѱ︦ѯ︦ѱ︦б︦а︯]

**Comment by typiconman** [comment]
Yes, this is a known bug. See issue #3.

**Comment by typiconman** [comment]
Closing this issue. Please put comments in issue #3.
