### ISSUE TITLE
Updating documentation for Unicode related informations

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [typiconman/fonts-cu#29]
The documentation have mentioned “Please note that combining Glagolitic letters (Glagolitic Supplement) will become available in Unicode 9.0”, but Unicode 9.0 is already released more than a half year ago. Please update the documentation.

**Comment by typiconman** [comment]
Good point. I'll take care of it.

**Comment by typiconman** [comment]
Fixed. See updated doc (attached).
[fonts-churchslavonic.pdf](https://github.com/typiconman/fonts-cu/files/943828/fonts-churchslavonic.pdf)

**Comment by KrasnayaPloshchad** [comment]
Alright.
