### ISSUE TITLE
Kerning issues with Ponomar Unicode

### ISSUE THREAD

**Issue by Mwvceu** [typiconman/fonts-cu#34]
![5fonts3words](https://user-images.githubusercontent.com/6507354/34491559-f7fa27d6-eff4-11e7-806e-aeb98dc4e8fa.png)
screenshot from LibreOffice

**Comment by typiconman** [comment]
Graphite kerning is hard to do. But yes, it should be done. See also #1.

**Comment by typiconman** [comment]
I updated the kerning, but the glagol + titlo + uk case is very difficult. Adding more kerning makes it look too spaced. Perhaps a better solution is to contextually substitute to a left-truncated uk in this case (see the last example). @Mwvceu @starover77 please comment.

![Screenshot from 2019-03-20 17-41-05](https://user-images.githubusercontent.com/5428695/54693417-a7ae1900-4b37-11e9-8c2b-e9169a1cd06e.png)

**Comment by starover77** [comment]
The contextual substitution with left-truncated uk looks good to me, and I think it would be an improvement to add it to the lookups. In all of the other demonstrated fonts, only the Pochaevsk and Irmologion fonts look OK with this character combination, which demonstrates that not all fonts are equal.

**Comment by typiconman** [comment]
Take a look at this.
![Screenshot from 2019-03-20 21-38-36](https://user-images.githubusercontent.com/5428695/54710371-9295b200-4b58-11e9-8948-b9e084db571d.png)

**Comment by typiconman** [comment]
The reported by @Mwvceu have been fixed. @starover77 Please check the kerning with the latest version of the font and see if there are any other issues.

**Comment by starover77** [comment]
Looks good to me.

**Comment by typiconman** [comment]
I think we rushed with closing this. Place an accent above the Uk creates problems. @starover77 please comment, especially regarding number 2.
![Screenshot from 2019-04-08 19-13-03](https://user-images.githubusercontent.com/5428695/55739765-615f2200-5a32-11e9-9c06-0bd625dbc46d.png)

**Comment by starover77** [comment]
I am not seeing any problems. What should I be looking for?

**Comment by typiconman** [comment]
Is the position of the acute accent correct? It looks strange, it almost collides with the ascender on the Uk. Here are some more examples:
![Screenshot from 2019-04-08 20-30-45](https://user-images.githubusercontent.com/5428695/55744267-38905a00-5a3d-11e9-9dd1-0c8c2f8f829f.png)

**Comment by starover77** [comment]
It does look a little bit close, but not so bad that I think it looks wrong. In my opinion, I don't think it's worth any further attention.

However, the fourth letter, with the kamora, looks wrong to me. (I suppose this is because I am used to seeing pre-Nikonian poluustav texts.) Contextually, I am used to seeing a kamora placed over a completely truncated Uk (both left and right ascenders shortened), but I suppose that Muscovite Synodal era typography doesn't typically use this contextual substitution.

**Comment by typiconman** [comment]
The Uk with the kamora is correct for Muscovite Synodal typography.

**Comment by starover77** [comment]
Yeah, I figured that. Modern typeface matrices had a lot less diversity that earlier forms, where truncated letters were used more extensively.

**Comment by typiconman** [comment]
So, should I keep the acute accent where it is now? Or return it to the raised position, as with the non-truncated version?

**Comment by starover77** [comment]
My vote: Leave it where it is now (lowered).

**Comment by typiconman** [comment]
Alright. Then we'll consider this closed.
