### ISSUE TITLE
Correct positioning of kamora in Ponomar

### ISSUE THREAD

**Issue by aleslavista** [typiconman/fonts-cu#35]
Hello,

The shape of circumflex doesn't seem very "convincing", too sans-serif, especially if compared to how it looks like in Menaion and Monomakh. Also the kerning needs tweaking in my opinion.

See attachment for visual proof.

Regards,
![circumflex](https://user-images.githubusercontent.com/33322424/36357947-264c3c7e-1506-11e8-88a2-68832b82ded6.png)

**Comment by typiconman** [comment]
Again, this how the kamora appears in current liturgical books. (Yes, *without* serifs).

The positioning over the Little Yus, on the other hand, could be tweaked a little, here I agree.

**Comment by aleslavista** [comment]
OK, thanks again for making it clear you're simply following an established pattern. I was unaware of it, sorry.

**Comment by typiconman** [comment]
Related to #10

**Comment by typiconman** [comment]
I think this is now fixed.
![Screenshot from 2019-03-17 13-36-35](https://user-images.githubusercontent.com/5428695/54489119-06fef580-48ba-11e9-8ce5-b34d8e2081e8.png)

**Comment by typiconman** [comment]
Fixed.

**Comment by aleslavista** [comment]
Where can I download is the updated version?

**Comment by typiconman** [comment]
For now, you can pull the latest code off GitHub and run ``make all``. I'll create updated binaries together with the beta version of the Mezenets font.
