### ISSUE TITLE
Shape of letter Zemlja in Menaion

### ISSUE THREAD

**Issue by aleslavista** [typiconman/fonts-cu#36]
Hello,

It looks like you decided to omit the "3"-shaped ZEMLJA altogether from MENAION, in all likelihood out of "archaicness" concerns. So the glyph of U+437 is identical to U+A641, however this defeats the purpose of having two different codepoints, and also goes against Unicode directives which direct font designers to implement archaic glyphs through codepoints explicitly reserved for archaic/Church Slavonic glyphs. By the same "archaicness" token you should have unified YERY U+44B with U+A651, YA U+44F with U+A657, provided that these glyphs never appear in USTAV manuscripts, as far as I know. Also you didn't unify DZELO U+455 with U+0643, which is startling since the earlier shapes of ZEMLJA and DZELO are almost alike.

My suggestion is for you to reintroduce the "3"-shaped ZEMLJA where it belongs, as this is, among other things, the shape that's almost universally used in transliterations from Glagolitic, i.e. Jagic's critical editions.

Regards,

**Comment by typiconman** [comment]
Here I agree with you. The Zemlya should be added to Menaion.

**Comment by typiconman** [comment]
@starover77 Do you want to tackle this issue?

**Comment by starover77** [comment]
Yes, I will add this to my TODO list. I will work on it later this evening and send it to you (@typiconman).

**Comment by starover77** [comment]
Done, and sent to Aleksandr for review.

**Comment by typiconman** [comment]
Fixed and closed.
