### ISSUE TITLE
Shape of Superscript VEDE in Monomakh

### ISSUE THREAD

**Issue by aleslavista** [typiconman/fonts-cu#38]
Hello,

Superscript VEDE in Monomakh looks like a square... the same is true for this font family, only Menaion is an exception, is it again a customary shape?

![superscript vede](https://user-images.githubusercontent.com/33322424/36566249-3666b380-1823-11e8-9aae-4c49e3928f5e.png)

**Comment by starover77** [comment]
Yes, this is the common traditional form of superscript Vedi. I assume that the letter took this form to avoid looking cramped or looking too much like the superscript Buki.

**Comment by typiconman** [comment]
This is another example of how the Menaion font is not well designed. The original designer must have shrunk the lowercase letters to make the combining letters.

**Comment by aleslavista** [comment]
But in Jagic's transliteration they don't look like a square And this book was printed in the mid-19th century. As soon as I spot the relevant example I'll post it here.

**Comment by aleslavista** [comment]
Here it is, avowedly the look is shoddy as it's a scanning of the original, this book has been out of print for half a century now, but we can make out that it's not a square.
![superscript vede 2](https://user-images.githubusercontent.com/33322424/36616741-23f9f1c2-18e5-11e8-9db2-7ca60f03d19b.png)

**Comment by starover77** [comment]
For Paleoslavic texts using the Ustav script, the superscript version of the letter "в" was basically what you see in the example you have shown us. -- BTW: I recognize the font in the example as one that was used in several Carpatho-Rusyn editions published at Mukachevo, particularly the Простопение, 1906 (see: http://ecmr.fi/Scanned_Chantbooks/prostopinie.pdf). I have also seen this font used in late 19th-century grammar books for Paleoslavic. It is quite utilitarian, but I think we can all agree that it was poorly designed.

However, for Church Slavonic texts (using the Poluustav script), the shape of the superscript "Vedi" evolved to look similar to a square to allow for easy distinction between the superscript "Buki" and "Vedi". It seems only logical that it progressed from a familiar Poluustav form to a more "skoropis" form, in this manner:
![2018-02-23 18_41_26-advance width metrics for ponomarunicode](https://user-images.githubusercontent.com/10853367/36622307-7b5a6110-18ca-11e8-81c0-6d71a55d13c8.png)
The second (square) form remains the "normal" shape of this character in Church Slavonic typography. Upon reflection, I think it is more historically accurate for us to use the standard shape of the letter as a superscript form in Ustav font designs.

**Comment by KrasnayaPloshchad** [comment]
Is it possible to add a style set to switch character variant for superscript Vede?

**Comment by typiconman** [comment]
@KrasnayaPloshchad Yes, it's possible. But I don't know if we need it. In which font do you want to see a new stylistic alternative?

**Comment by aleslavista** [comment]
Do you feel it'd be OK to typeset Codex Marianus with the shape implemented in Monomakh even though it doesn't appear in Jagic's work?

You're certainly more qualified than I do to discern such issues.

**Comment by typiconman** [comment]
Personally, I'm not why reproducing Jagic's typeface is an important goal. 19th century editions of Church Slavonic texts are not particularly know for high quality type anyway.

**Comment by aleslavista** [comment]
Because the square-like shape is not particularly "intuitive". I was startled the first time I saw, I thought it was a bug, but then I'm not an expert of Slavonic typography so my hunch may be deceptive.

**Comment by aleslavista** [comment]
For the record, in Shafarik the shape is as in Menaion.

**Comment by typiconman** [comment]
@aleslavista @starover77 What's the take on this? Do we want to change the shape of the superscript Vedi in Monomakh?

**Comment by starover77** [comment]
Well, I don't have much use for the Monomakh font (for artistic reasons), but if we are going to toss aside the traditional superscript form of the letter Zemlya, we might as well do the same for the superscript Vedi. Do you need me to design the character?

**Comment by typiconman** [comment]
@starover77 Yes, if you can design a new superscript Vedi, that would be fantastic.

**Comment by starover77** [comment]
I will add this to my TODO list and I hope to get that done this evening.

**Comment by typiconman** [comment]
This is now fixed.
