### ISSUE TITLE
Implement collision avoidence for Pokrytie

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [typiconman/fonts-cu#40]
Seen from the web site, I think Ponomar and Fedorovsk fonts should create collision avoidences to make Pokrytie not touch other letters. For example, in the word Хрⷭ҇то́съ, the letter рⷭ҇ should has a gap (as hair space) after Х while it is combining with Pokrytie.

**Comment by typiconman** [comment]
Duplicate of #34?

**Comment by KrasnayaPloshchad** [comment]
Yes.
