### ISSUE TITLE
Deprecate SIL Graphite / Депрекация фич Graphite

### ISSUE THREAD

**Issue by typiconman** [typiconman/fonts-cu#46]
SIL Graphite features were added to our fonts primarily for software that does not support OpenType (mainly LibreOffice). Most software now supports OpenType features (e.g., LibreOffice). Therefore users get no additional functionality from SIL Graphite features.

Moreover, SIL Graphite requires use of TrueType fonts, which generate lower quality (quadratic splines) than PostScript fonts (cubic splines), and requires us to maintain a TTF layer parallel and GDL code. This makes it difficult to add new glyphs from the point of view of maintainability.

Therefore it is proposed to declare SIL Graphite features deprecated. It is further proposed to remove the TTF layer and the GDL code in order to simply the font. This would mean that we would provide only PostScript fonts.

However, maybe some users still require use of the TrueType layer / SIL Graphite features?

Please vote in this poll. 
The options are: 1. remove the TTF layer and all SIL Graphite features; 2. keep the TTF layer and Graphite features, but deprecate them (add no new features); 3. continue to support Graphite features (by adding new features) -- in this case, pull requests will be welcome.

The poll will be open until Pascha 2019, at which point we'll make a decision.

[![](https://api.gh-polls.com/poll/01D65Q3615CN2ZQCAP087Y6Z87/Remove%20TTF%20layer%20and%20SIL%20Graphite%20features)](https://api.gh-polls.com/poll/01D65Q3615CN2ZQCAP087Y6Z87/Remove%20TTF%20layer%20and%20SIL%20Graphite%20features/vote)
[![](https://api.gh-polls.com/poll/01D65Q3615CN2ZQCAP087Y6Z87/Keep%20TTF%20layer%2C%20declare%20Graphite%20features%20deprecated)](https://api.gh-polls.com/poll/01D65Q3615CN2ZQCAP087Y6Z87/Keep%20TTF%20layer%2C%20declare%20Graphite%20features%20deprecated/vote)
[![](https://api.gh-polls.com/poll/01D65Q3615CN2ZQCAP087Y6Z87/Continue%20to%20maintain%20TTF%20layer%20and%20Graphite%20features)](https://api.gh-polls.com/poll/01D65Q3615CN2ZQCAP087Y6Z87/Continue%20to%20maintain%20TTF%20layer%20and%20Graphite%20features/vote)

Фичи графит были включены в наши шрифты для программ, которые не поддерживают OpenType (например, LibreOffice). Так как современные версии этих программ поддерживают OpenType, то поддержка фич Graphite теряет актуальность. При этом, для поддержики фич Graphite мы обязаны содержать TrueType версии шрифтов и файлы GDL. В целях упрощения поддержки шрифтов, предлагается удалить и TrueType слой из шрифтов, и файлы GDL, и прекратить поддержку SIL Graphite. Но может быть кто-то еще пользуется Graphite?

Просьба проголосовать за опции: 1. удалить SIL Graphite фичи и слой TrueType; 2. оставить слой TrueType, но объявить Graphite deprecated; 3. продолжать поддержку SIL Graphite (в этом случае будут необходимы pull request для дальнейшей поддержки).

**Comment by while0pass** [comment]
Случайно проголосовал за второй и третий вариант. Не знаю, как снять свои голоса. Я бы сохранил файлы GDL, но не поддерживал версию TrueType в надежде, что кто-нибудь все же реализует поддержку CFF для SIL Graphite. Да, такие запросы уже были несколько раз за последние 15 лет и разработчики SIL Graphite всякий раз отвечали, что не планируют тратить на это свое время, хотя не против, если кто-нибудь другой поможет это сделать. Кроме того в LibreOffice уже несколько лет, как появилась возможность включать stylistic sets, что до некоторой степени покрывает произвольные Graphite фичи. В этом отношении, ожидать не очень осмысленно. Тем не менее, не уверен, что до сих пор возможно отображение арабских чисел цсл буквами средствами самого OpenType, а это было бы полезно. В общем, сама технология Graphite ещё не кажется устаревшей. Если возможно просто заморозить GDL-файлы, но не удалять их, я бы предпочел такой вариант. А от TrueType, да, наверное уже лучше отказаться.

**Comment by typiconman** [comment]
@while0pass Проблема в том, что Graphite фичи можно прописать только к TTF шрифтам. Так что GDL исходник без TrueType версии шрифта будет как колесо без машины.

Конвертация арабских чисел в кириллическую цифирь средствами OpenType действительно не выполнить. Но скажем в LibreOffice поддерживается нумерация страниц кириллической цифирью, так что это наверное не очень актуально. Разве что для MS Office.

**Comment by while0pass** [comment]
@typiconman То, что все Graphite-таблицы, а не только фичи до сих пор можно инкорпорировать только в TTF-шрифты, мне известно. Вместе с тем с OT-CFF-шрифтами тут нет принципиальной несовместимости, проблема лишь в том, что основные разработчики SIL Graphite никогда не рассматривали реализацию поддержки OT-CFF как хоть сколько-нибудь приоритетную задачу. И нет, GDL-исходники без TT все же не колесо без машины, а скорее двигатель без шасси и корпуса :) Ладно, в конце концов код можно будет воскресить из недр репозитория, если в этом вновь появится необходимость, а поддерживать TTF точно нет смысла.

**Comment by typiconman** [comment]
@while0pass Возможно такое решение -- перевести все слои TTF и исходный код GDL в новый репозиторий fonts-cu-legacy, и заморозить его. Кому нужен графит и TrueType, могут взять оттуда.

А здесь продолжить дальше развитие пакета, в том числе и пополнив новыми шрифтами, как в #47.

**Comment by while0pass** [comment]
@typiconman Да, это хороший вариант.

**Comment by typiconman** [comment]
Support for SIL Graphite has now been moved to the [legacy repository](https://github.com/slavonic/fonts-cu-legacy).
