### ISSUE TITLE
Capital Letter Uk U+0423 should not have circular component

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [typiconman/fonts-cu#5]
Wikipedia article refered that [Uk](https://en.wikipedia.org/wiki/Uk_(Cyrillic)) can implement all-caps style by inputing О+У, but when I displaying it with Ponomar Unicode, it looks like ОꙊ. What if implementing all-caps styled Uk?

**Comment by typiconman** [comment]
What do you mean by caps UK? U+A64A Ꙋ?

**Comment by KrasnayaPloshchad** [comment]
No, I mean by [U+041E, U+0423], but U+0423 still has the same shape as U+A64A in this case.

**Comment by typiconman** [comment]
Yes. U+041E U+0423 produces the digraph ОУ, as expected. What character are you trying to represent?

**Comment by KrasnayaPloshchad** [comment]
To my eyes, the circle in U+0423 should be removed in this case.

**Comment by starover77** [comment]
Aleksandr, I think he has a valid point. I think U+0423 should not be designed as a digraph. See the shape that we use in the Fedorovsk font.

**Comment by typiconman** [comment]
So what you're saying is that the glyph for U+0423 should not be the same as the glyph for U+A64A? Could you submit a picture from a liturgical text that shows how the glyph should be shaped.

**Comment by KrasnayaPloshchad** [comment]
Well, I just think U+0423 should giving an alternate shape after U+041E, but I don’t know what the exactly feature can be used to produce the effect. Maybe the `liga` feature can do it, but what if using a contextual sensetive feature? I have no idea.

**Comment by typiconman** [comment]
It could be done with stylistic sets, or we can even replace the glyph itself. But first we need an example from a source where the ОУ is used.

**Comment by KrasnayaPloshchad** [comment]
I remember I have got EB Garamond 12 font, this font seems having “ligatures” for ff, fi, fl, but I haven’t found any standard ligature for them when I open with FontForge, instead I found some contextual forms that can be used for generating the effect. May you can try to use this way for U+0423.

**Comment by typiconman** [comment]
OK, look on page 3 here:
http://ponomar.net/files/part1_vigil.pdf
in the word ОУТРЕНѦ.

**Comment by starover77** [comment]
They typed it the same way on page 65. I'm still not convinced that it is proper form, but since the Synod Typografiia observed this usage, I suppose we can leave the font as it is. However, I think that the form we have used in the Fedorovsk font is the more logical form.

**Comment by typiconman** [comment]
I am willing to support both alternatives, but we need examples of usage, so that we can base the character design on something.

**Comment by KrasnayaPloshchad** [comment]
> OK, look on page 3 here:
> http://ponomar.net/files/part1_vigil.pdf
> in the word ОУТРЕНѦ.
I also found it on the cover, in the word ОУ҆ПОТРЕБИТЕЛЬНЫХЪ

**Comment by KrasnayaPloshchad** [comment]
I got it again in this file, on page 4—5:
http://ponomar.net/files/kozmin.pdf
Futhremore, I think maybe you should also implementing all-caps styled ukŭ for U+0478.

**Comment by starover77** [comment]
Several Slavonic scholars have discussed this at great length in years past during the development phase of Church Slavonic fonts. In the earlier stage of Unicode, the character U+0478/0479 was introduced and was used for a while. However, after presented with actual usage in liturgical texts, where it may be necessary or desirable to use color separation (red for the first glyph, and black for the second plus diacritic), these same Slavonic scholars realized that they had made a mistake in treating the two glyphs as a single unified character. Thus, in a later version of Unicode the character U+0478/0479 has been deprecated (discontinued) and is no longer recommended for use. (The composite characters remain in the font only for support of texts that used that character in years past.)

Now it is strongly recommended that people typeset ОУ, Оу and оу as TWO characters, and then let the font rendering engine do the work of substituting the correct letter forms (such as the Narrow ON for the lower case form). TrueType and OpenType font technology has programmed by the Ponomar Project to work this way, and we have also included sorting tables so that the two characters will correct sort between Т and Ф. -- Also, by typesetting these as two characters, you have more control over how the text will look and behave.

**Comment by KrasnayaPloshchad** [comment]
It’s clear that only U+0423 should implementing an alternate glyph.

**Comment by starover77** [comment]
I agree with you. U+0423 should be redesigned to remove the circle. U+0423 (У) is a monograph glyph, not a digraph. I think that when we designed the Ponomar Unicode font, we were inattentive to this detail. Aleksandr, can we fix this?

**Comment by KrasnayaPloshchad** [comment]
Seen from part1_vigil.pdf, I think despite U+0423 is redesigned, the previous glyph should be keep as subsitution glyph, presented via proper feature tag.

**Comment by KrasnayaPloshchad** [comment]
> Seen from part1_vigil.pdf, I think despite U+0423 is redesigned, the previous glyph should be keep as alternate glyph, presented via proper feature tag.

Now I think the existed glyph can be keep as Style Set `ss01...ss20`, this feature can also used for the letter estĭ, seen from [this page](http://tmora.org/resources/russian-language-resources/).

**Comment by typiconman** [comment]
Based on discussion here and in private, it's been decided to change the glyph at U+0423 and to make the current version of the glyph a stylistic alternative.

**Comment by KrasnayaPloshchad** [comment]
The current version of the glyph should also added as style set. Because the current version of M$ Word cannot access the stylistic alternative feature but can access style set.

**Comment by typiconman** [comment]
@starover77 @KrasnayaPloshchad please check. I have uploaded a revision.
@starover77 where is a good place to put the stylistic alternative in the PUA? I have tentatively used U+E37A, which seems to be unused in your R&D font. Please confirm.

**Comment by starover77** [comment]
U+E37A works well for me, but let me get some clarification. You want to move Capital Letter Uk U+0423 (У with a small o) to U+E37A (which I am strongly in favor of doing), and replace it with an У without a small o?

**Comment by typiconman** [comment]
@starover77 Yes. We take the Uk glyph that was at U+0423 and place it at U+E37A. At U+0423 we place a glyph for U. Please look at the current version of the font for the glyph design. It is based on the Synodal square-note Obikhod.

**Comment by starover77** [comment]
OK, go ahead and make the changes. It is fine with me. Thanks!

**Comment by typiconman** [comment]
Is new glyph design OK?

**Comment by starover77** [comment]
I will look at it in the morning. I just turned the computer off for the night. :-)
Sent from Yahoo Mail on Android 
 
  On Sun, Mar 20, 2016 at 10:17 PM, Aleksandr Andreev<notifications@github.com> wrote:   
Is new glyph design OK?

**Comment by KrasnayaPloshchad** [comment]
Hey Aleksandr, I can see this change, however this glyph should making small improve:
![Screenshot](http://chuantu.biz/t2/33/1458553858x3340469735.png)

**Comment by KrasnayaPloshchad** [comment]
Considering the previous glyph of U+0423 looks the same as U+A64A, I think the alternate glyph for U+0423 can refered the glyph used in U+A64A.

**Comment by typiconman** [comment]
I updated the glyph. Please check.
@KrasnayaPloshchad Yes I will update U+)40E as well. I think mapping U+0423 -- ss --> U+A64A is a bad idea for things like search of PDF files and text extraction (see discussion of Adobe Glyph List in UTN 41). It would be better to put it into PUA. 
If everything is OK, I will fix the kerning and add the ss substitutions.

**Comment by KrasnayaPloshchad** [comment]
OK, It looks so good. BTW is it possible of coping reference from U+A64A to a PUA code point?

**Comment by typiconman** [comment]
@KrasnayaPloshchad Yes, in principle you can do references in FontForge. I'm not sure why we've never done that with our fonts.

**Comment by KrasnayaPloshchad** [comment]
> I'm not sure why we've never done that with our fonts.

This will making the maintance easier. If you are using one glyph reference to other related glyphs, when you making a modification, other glyphs would immediately following this revision.

**Comment by typiconman** [comment]
@KrasnayaPloshchad @starover77 Please review. I added kerning data, mappings in SALT table. Also added a variant of U+040E at U+E37B. Added Graphite feature altu. Please make sure everything works OK.

**Comment by KrasnayaPloshchad** [comment]
OK, it’s good. I generated an OTF font file to test. BTW I think you can using glyph reference for any other accented letters, this would reduce the concentration for future maintance.
[1](http://chuantu.biz/t2/45/1459411425x3340469574.png)
[2](http://chuantu.biz/t2/45/1459411754x3340469574.png)

**Comment by typiconman** [comment]
OK. If there are no further comments, we will consider this fixed.

**Comment by KrasnayaPloshchad** [comment]
I think this is fixed.
@starover77 WDYT?

**Comment by starover77** [comment]
It looks fine to me.

**Comment by KrasnayaPloshchad** [comment]
👏

**Comment by KrasnayaPloshchad** [comment]
This design get the appriciate result when I used to browsing the following pages:
https://en.wikipedia.org/wiki/Cyrillic_script
https://en.wikipedia.org/wiki/Early_Cyrillic_alphabet
