### ISSUE TITLE
Change shape of Cross sign in Ponomar

### ISSUE THREAD

**Issue by EliseyP** [typiconman/fonts-cu#50]
Need for new Cross symbol like in "Orthodox.tt eRoos" font: \u2020  
![Kross](https://user-images.githubusercontent.com/38728959/57928454-793f8680-78b9-11e9-83e1-4143c26523fa.png)

It have very nice proportions!

**Comment by starover77** [comment]
I'm sorry, but I beg to differ with you in regard to proportions. The Cross as depicted in the Orthodox.tt eRoos font lacks consistency of weight and balance. First of all, all four lines should be of equal weight (thickness). Second, the section above the long horizontal beam should form a perfect 2-bar Cross, with equal proportions like the + (plus) sign. Third, the diagonal bar should only extend to the right and left to the same "longitude" as the top horizontal bar extends. Fourth, the wide horizontal bar should not be much more than double the length of the bar above it. Finally, the vertical beam should not be too long. Please look at the following two images:
https://i.pinimg.com/originals/ba/e1/c1/bae1c1f2d8b72f0650e3a7cbf4c4e9b2.png

https://lh3.googleusercontent.com/-f0o7nXH0S14/TYjNOfcZNTI/AAAAAAAAAFY/0Ct9TB4LCSI/s1600/Cruz-Ortodoxa1.png

**Comment by typiconman** [comment]
По-моему @starover77 прав. У символа в Orthodox.tt eRoos действительно неверные пропорции.

Having said, the shape of the Cross symbol in our fonts is not proportional either.
![cross](https://user-images.githubusercontent.com/5428695/57965127-527c6100-7948-11e9-868b-3c31bc9722a5.png)

**Comment by typiconman** [comment]
@starover77 Please provide some input on this.

**Comment by typiconman** [comment]
I fixed the shape of the Orthodox Cross in Ponomar and also changed the shape of the "Dagger" U+2020. @starover77 and @EliseyP, please comment.
Also, do these characters need to be changed in the other fonts?

**Comment by EliseyP** [comment]
Отлично! А можно посмотреть обновленную форму? 
С Праздником всех!

**Comment by typiconman** [comment]
@EliseyP выкладывать шрифты на GitHub запрещено, но я выложил для Вас [здесь](https://drive.google.com/file/d/1To5nS69ipCpJ_ADluPfRFTOCXY13HZnZ/view?usp=sharing).

**Comment by typiconman** [comment]
Нет, в релизе его нет, оно в ветке issue-fixes.

**Comment by EliseyP** [comment]
>> Also, do these characters need to be changed in the other fonts?
В других гарнитурах похоже тоже можно поменять форму. Например "Pochaevsk Unicode" - тоже пропорции есть куда улучшить (на мой субъективный взгляд).

**Comment by typiconman** [comment]
Исправил символы дротика и православного креста во всех шрифтах. Вот как выглядит:
![image](https://github.com/typiconman/fonts-cu/assets/5428695/067056ea-adda-497f-84b9-f2aabf56e882)
Комментируйте.

**Comment by typiconman** [comment]
Fixed.
