### ISSUE TITLE
Update the documentation for LibreOffice 

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [typiconman/fonts-cu#51]
LibreOffice 6.2 implemented the Font Feature dialog, which provides graphical interface to switch font feature, and accessable at the Character dialog, so I suggest updating documentation to reflect this change.

See: https://wiki.documentfoundation.org/ReleaseNotes/6.2

**Comment by typiconman** [comment]
Thanks for pointing it out. I need to upgrade to 6.2 and give it a test!

**Comment by typiconman** [comment]
Fixed and closed.
