### ISSUE TITLE
Incorrent red letter view in HTML (macOS)

### ISSUE THREAD

**Issue by GeorgePlotnikov** [typiconman/fonts-cu#54]
Hi @typiconman ,

The Indiction and Vertrograd fonts have bad view on my Mac in the safari v13.0.5

<img width="407" alt="image" src="https://user-images.githubusercontent.com/22812032/79431540-41fabd80-7fd3-11ea-94d9-1196a6cac567.png">

**Comment by typiconman** [comment]
What's the problem? Here is what it looks like on my Linux Mint machine
![fonts](https://user-images.githubusercontent.com/5428695/79438815-b25a0c80-7fdc-11ea-8aff-f3b2301fa8e7.png)
.

**Comment by typiconman** [comment]
Never mind, I figured out the problem and fixed. Thanks for reporting it.
