### ISSUE TITLE
Incorrect font view on Mac in MS Word

### ISSUE THREAD

**Issue by GeorgePlotnikov** [typiconman/fonts-cu#55]
Hi @typiconman,

see the view how does the font Ponomar look on Mac in the MS Word

<img width="1077" alt="Screenshot 2020-04-16 at 11 20 28" src="https://user-images.githubusercontent.com/22812032/79432683-d6b1eb00-7fd4-11ea-84d4-918b7be7d6f6.png">

**Comment by typiconman** [comment]
Very strange. Unfortunately, I cannot test it, since I don't have a Mac.

Does the same thing happen with the other fonts from our site?

**Comment by typiconman** [comment]
Cannot test, since I have no access to a Mac.

**Comment by GeorgePlotnikov** [comment]
@typiconman I can

**Comment by typiconman** [comment]
Ok. Pull requests are welcome.

**Comment by EliseyP** [comment]
On Monterey (in VMWare) CSL text showed correctly, but **keyboard driver** not accessible for MSWord, and Notes, TextEdit. Driver showed at tray menu, but not selectable for this application.   
![Screenshot_20220129_100315](https://user-images.githubusercontent.com/38728959/151651851-55239a30-1b3e-42b2-a06e-c4dd36e3ff87.jpeg)  

For Libre Office, Terminal, Adobe InDesign all work fine.   

![Screenshot_20220129_101240](https://user-images.githubusercontent.com/38728959/151651861-22f16c22-8a81-4aa7-b321-e103f80f8f2d.jpeg)

**Comment by typiconman** [comment]
Is it a bug in MS Word?

**Comment by GeorgePlotnikov** [comment]
Just checked on the latest versions (macOS & ms word). Seems works fine. Close then
<img width="869" alt="image" src="https://user-images.githubusercontent.com/22812032/152503946-e020da7a-d0d7-47ca-b6f5-fed1783356a1.png">

**Comment by EliseyP** [comment]
What about CSL keyboard driver for MSWord in Mac for you? Fonts showed
correctly, but can you type csl text with diacritics etc in MSWord?

Пт, 4 февр. 2022 г. в 12:21, George Plotnikov ***@***.***>:

**Comment by GeorgePlotnikov** [comment]
@EliseyP can you please gimme some key combinations to try

**Comment by EliseyP** [comment]
F.e. "a + shift + 7" (a with iso)



Пт, 4 февр. 2022 г. в 12:26, George Plotnikov ***@***.***>:

**Comment by GeorgePlotnikov** [comment]
im not sure I understand how it works...

**Comment by EliseyP** [comment]
You should select keyboard driver for Church Slavic language (in tray meny, in language selector, as you can see at sreenshots in my past comment). And you can type csl text with all specific things (diacritics etc). 

I wrote, that in case LibreOffice I can select Church Slavic language and type all, what I want (see on second sreenshot). But for several applications, MSWord and so on, I can't ever select Church Slavic language. 

I can only type russian letters, that's common for both languages - russian and csl. Or I can copy paste typed text with all diacritics in anoter application (Libre Office). Or open previously typed such text. 

That's situation in my Monterey Mac (in VMware). How about your system?

**Comment by GeorgePlotnikov** [comment]
@EliseyP I think it works
<img width="680" alt="Screen Shot 2022-02-07 at 10 05 42 PM" src="https://user-images.githubusercontent.com/22812032/152854876-074f606b-3942-4456-bf63-2c2b2b9b698e.png">

**Comment by EliseyP** [comment]
You type this in MSWord? And do you set font for this fragment?

**Comment by GeorgePlotnikov** [comment]
@EliseyP OMG yes, how difficult it is 😓 

<img width="599" alt="image" src="https://user-images.githubusercontent.com/22812032/152855648-2e5c0554-07d4-4e19-a882-968c038e1bd9.png">

**Comment by EliseyP** [comment]
All work fine. Keyboard layout must be installed for system level.  

![Screenshot_20220207_233112](https://user-images.githubusercontent.com/38728959/152867397-554f40b6-d65a-4f62-9184-ea5be4c7f25c.jpeg)
