### ISSUE TITLE
Лигатура для Т прописной и о-титла

### ISSUE THREAD

**Issue by EliseyP** [typiconman/fonts-cu#58]
При написании слова **Троица** с прописной (в начале предложения/стиха и т.д.) происходит такое наложение элементов.   
![Screenshot_20201101_204909](https://user-images.githubusercontent.com/38728959/97810336-28297b00-1c84-11eb-8941-3e9ae92cd714.jpeg)    
Возможно, правда, так и задумано. Не уточнял, как это выглядит в рукописных/печатных книгах.

**Comment by typiconman** [comment]
Это баг.

**Comment by typiconman** [comment]
@EliseyP можете прислать пример из печатных книг, как должна выглядеть эта комбинация?

**Comment by EliseyP** [comment]
Ищу, ищу. Редкий, понятное дело случай. Спрашивал даже у знакомых
иконописцев, как могла бы она выглядеть. Пока ничего. Предположу, что
«пострадает» горизонтальная часть буквы Т (как часть у буквы у с Варей).
Либо будет объединение.

Чт, 8 июля 2021 г. в 18:44, Aleksandr Andreev ***@***.***>:

**Comment by typiconman** [comment]
Хотелось бы увидеть пример, перед тем как рисовать.

**Comment by EliseyP** [comment]
Вот, для шрифта `Orthodox.tt Ucs8` такой вариант: 
![2021-07-08_19-08-55](https://user-images.githubusercontent.com/38728959/124955883-17ee4a80-e020-11eb-807f-122ce065bf9a.png)

Покрытие высоко, но в пределах высоты шрифта, такой же высоты, как, скажем, `Аз+Исо`.

**Comment by EliseyP** [comment]
Немного экзотично, но возможно вот такой вариант:
![2021-07-08_21-55-16](https://user-images.githubusercontent.com/38728959/124976110-7ffc5b00-e037-11eb-9090-3f805606d1f9.png)

Исполнение корявое, но общий принцип, думаю, понятен. Не помню, где точно я это видел, правда.

**Comment by EliseyP** [comment]
Иконописцы посоветовали такой вариант: 
![2021-07-08_22-38-57](https://user-images.githubusercontent.com/38728959/124981743-978b1200-e03e-11eb-94a9-42563c350d96.png)

**Comment by typiconman** [comment]
> Иконописцы посоветовали такой вариант:
> ![2021-07-08_22-38-57](https://user-images.githubusercontent.com/38728959/124981743-978b1200-e03e-11eb-94a9-42563c350d96.png)

Да, пожалуй этот вариант самый приемлемый.

**Comment by mamyt** [comment]
I have attached other similar cases where there is a collision between a capital letter and the titlo that should also be fixed. As well, there are a few other collisions that would need to be fixed.
[Collision between Titlo and Capital Letters.pdf](https://github.com/typiconman/fonts-cu/files/6797535/Collision.between.Titlo.and.Capital.Letters.pdf)

**Comment by starover77** [comment]
Here is my contribution, where I test the positioning of selected titly and kerning.
[TTitlo and Kerning test doc.pdf](https://github.com/typiconman/fonts-cu/files/6797720/TTitlo.and.Kerning.test.doc.pdf)

**Comment by typiconman** [comment]
> I have attached other similar cases where there is a collision between a capital letter and the titlo that should also be fixed. As well, there are a few other collisions that would need to be fixed.
> [Collision between Titlo and Capital Letters.pdf](https://github.com/typiconman/fonts-cu/files/6797535/Collision.between.Titlo.and.Capital.Letters.pdf)

@mamyt this was done on what platform?

**Comment by EliseyP** [comment]
It's bug? - kamora position seems left shifted.  
![image](https://user-images.githubusercontent.com/38728959/125229711-fe7b2600-e2df-11eb-9231-cc27c874c02d.jpeg)

**Comment by mamyt** [comment]
Windows 10 (latest release) and Microsoft Word 2019 (latest build) with all
advanced font features selected.

**Comment by typiconman** [comment]
> It's bug? - kamora position seems left shifted.
> ![image](https://user-images.githubusercontent.com/38728959/125229711-fe7b2600-e2df-11eb-9231-cc27c874c02d.jpeg)

По-моему так решили при дизайне шрифта (центрирование по отношению к основанию, а не к верхней части). Но можно изменить.

**Comment by EliseyP** [comment]
Похоже, что относительно основания сдвиг.

**Comment by EliseyP** [comment]
Временное решение для XeLaTeX:  
```
\XeTeXinterchartokenstate=1
% char class for Тr
\newXeTeXintercharclass \mycharclassTr
\XeTeXcharclass `Т \mycharclassTr
\XeTeXcharclass `р \mycharclassTr
% char class for OTitlo
\newXeTeXintercharclass \mycharclassOTitlo
\XeTeXcharclass `ⷪ \mycharclassOTitlo
\XeTeXcharclass `҇ \mycharclassOTitlo
% def interchartokes
\XeTeXinterchartoks \mycharclassTr \mycharclassOTitlo = {\kern4pt}
\newcommand{\Troi}[1]{Трⷪ҇\kern-3.5pt #1}
```
Соответственно, в тексте команда `\Troi{цѣ}` даст такой вывод:  
![Screenshot_20220318_224632](https://user-images.githubusercontent.com/38728959/159073572-96b6188e-1f4f-4e1d-9b36-fc3ba7cdfd40.jpeg)

**Comment by EliseyP** [comment]
Соответственно для слов под с-титлом Трисвятое и т.п.:  
```
% char class for STitlo
\newXeTeXintercharclass \mycharclassSTitlo
\XeTeXcharclass `ⷭ \mycharclassSTitlo
\XeTeXcharclass `҇ \mycharclassSTitlo
\XeTeXinterchartoks \mycharclassTr \mycharclassSTitlo = {\kern4pt}
\newcommand{\Trisvjat}[1]{Трⷭ҇\kern-3.5pt т#1}
```
команда `\Trisvjat{о́е}` даст:  
![Screenshot_20220318_225825](https://user-images.githubusercontent.com/38728959/159075048-370a0b02-f4f0-4500-bae3-26818f693790.jpeg)

**Comment by EliseyP** [comment]
Для ѧ + камора есть автоматическое решение для XeLaTeX:  
```
\XeTeXinterchartokenstate=1
\newXeTeXintercharclass \mycharclassya
\XeTeXcharclass `ѧ \mycharclassya
\newXeTeXintercharclass \mycharclassKamora
\XeTeXcharclass `̑ \mycharclassKamora
\XeTeXinterchartoks \mycharclassya \mycharclassKamora = {\kern-2pt}
```
![Screenshot_20220318_233648](https://user-images.githubusercontent.com/38728959/159079837-5dd7668a-b508-4cd9-9041-26bdcd3b7cee.jpeg)

**Comment by StefanPeev** [comment]
@KrasnayaPloshchad Применение лигатуры к шрифту, при условием, что такие лигатуры отсутствуют в оригинальных рукописях, не является хорошей идеей, особенно если шрифт также используется в академических научных публикациях. Я бы сказал то же самое о добавлении hair space. Возможно, лучшим решением будет кернинг или контекстное горизонтальное позиционирование через GPOS table. Что-то в духе того, что предлагали иконописцы.
Я всегда придерживался идеи, что шрифт должен максимально отражать графическую структуру оригинала. Поэтому в обоих глаголических проектах, над которыми я работаю, я стремлюсь воспроизвести именно те лигатуры, которые действительно присутствуют и в Зографском Евангелии, и в Ассеманиево Евангелии, чтобы получить наиболее адекватное воспроизведение между оригинальным и современным изданием.

Шрифт основан на дизайне графических символов в Зографском Евангелие
![Codex_Zographensis](https://github.com/typiconman/fonts-cu/assets/12949369/f55b1105-792c-40bc-8e3c-48e3b6fad06b)

Однако если шрифт используется не для воспроизведения оригинальных рукописных или печатных текстов, а без учета связи с историческими памятниками, то в него можно включать всевозможные типографские штучки.

**Comment by typiconman** [comment]
My glyph looks OK.
![image](https://github.com/typiconman/fonts-cu/assets/5428695/1c34b65a-0244-4bfb-a9b3-cbf3aca70a76)

Can anyone else reproduce this bug?

**Comment by starover77** [comment]
I tested all of the Ponomar Project Slavonic Unicode fonts using MSOffice and LibreOffice in Windows 11, as well as LibreOffice in Linux Mint. In all cases the Kamora (Combining Inverted Breve, U+0311) displayed correctly. I could not reproduce the problem.

**Comment by EliseyP** [comment]
Now in LibreOffice 24.2 Linux Debian **yat + kamora** looks fine too.

**Comment by typiconman** [comment]
Fixed the kerning of Ge and Te in Ponomar
![image](https://github.com/typiconman/fonts-cu/assets/5428695/52f71bf9-66df-404f-9bf1-f3d54b842474)
and in Pochaevsk
![image](https://github.com/typiconman/fonts-cu/assets/5428695/92d8518f-1a11-4a99-892d-3036728246cd)

**Comment by typiconman** [comment]
Первая попытка:
![image](https://github.com/user-attachments/assets/eac93a0b-65a7-468e-a16f-433c501f095c)
По идее надо бы еще снять кернинг после заглавной. @EliseyP прокомментируйте.

**Comment by EliseyP** [comment]
>> Первая попытка:    

Прекрасно!   
>> снять кернинг после заглавной    

Не совсем понятно, `снять = убрать`?

**Comment by typiconman** [comment]
Да, убрать горизонтальный кернинг. Впрочем, не всегда получается удачно. Вот так:
![image](https://github.com/user-attachments/assets/2d441c80-7216-4bd6-a542-a73b63763314)
Есть ли еще какие-то случаи, которые надо учесть?

**Comment by EliseyP** [comment]
Горизонтальный кернинг - действительно бросается в глаза после заглавных в этих примерах.   


Других сочетаний пока не припомню.

**Comment by typiconman** [comment]
Какой вариант оставляем, первый или второй?

**Comment by EliseyP** [comment]
Если касательно кернинга после заглавной, то прошу прощения, - наоборот - писал комментарий, имея в виду как раз первый вариант, а он похоже и есть с кернингом. Так что оставть на мой взгляд лучше первый вариант, с кернингом после заглавной. Иначе очень заметно расстояние (это как для сочетаний с прописной Т, которые выше рассматривались).

**Comment by typiconman** [comment]
Тогда давайте остановимся на вот этом варианте:
![image](https://github.com/user-attachments/assets/ddfc8816-377b-4546-87a3-f34d98f1ecf6)
Остается недоработка с Ѱаⷧ҇, здесь видимо надо рисовать специальную лигатуру.
@starover77 please also comment.

**Comment by EliseyP** [comment]
Отлично!

**Comment by EliseyP** [comment]
>> Остается недоработка с Ѱаⷧ҇, здесь видимо надо рисовать специальную лигатуру.   


Посмотрите, еще как будет с заглавной титлованое Зач. Ч под титлом.

**Comment by typiconman** [comment]
Да, За(ч) отображается корректно, а вот Ро(з)[вод фиты в знаменных партитурах] я подправил:
![image](https://github.com/user-attachments/assets/f65ddbc9-ae48-4303-8dc3-0a95b2871a52)
Подумайте, есть ли еще какие-то случаи.

**Comment by EliseyP** [comment]
Может быть для Ѱаⷧ҇  - л оставить без покрытия и сдвинуть вправо?

![Screenshot_20240715_105841](https://github.com/user-attachments/assets/8137929d-4c31-482e-8117-c6eba75b7f10)

**Comment by typiconman** [comment]
Без покрытия странно выглядит. Что можно сделать, на мой взгляд:
1. обрезать справа Пси.
2. подвинуть покрытие наверх.
3. слить покрытие с Пси
В последних двух случаях придется рисовать лигатуру.

**Comment by EliseyP** [comment]
Согласен. Можно попробовать п.1 - посмотреть на результат.

**Comment by typiconman** [comment]
Вот так:
![image](https://github.com/user-attachments/assets/ccea0353-76f9-491c-85b5-40f97c938d8c)

**Comment by EliseyP** [comment]
Прекрасно.

**Comment by typiconman** [comment]
Fixed and closed.
![image](https://github.com/user-attachments/assets/a6c5b0dd-5861-446c-882a-37fea9e30976)

**Comment by typiconman** [comment]
Also added truncated Psi to Triodion:
![image](https://github.com/user-attachments/assets/f3f4d3e0-c9d5-4c82-b081-c3b371593a6c)
