### ISSUE TITLE
TeX: CMYK colors.

### ISSUE THREAD

**Issue by EliseyP** [typiconman/fonts-cu#59]
Our typography wanted pdf with cmyk colors.   
We can redefine kinovar color \definecolor{kinovar}{cmyk}{N,N,N,N}.  
(I set color-model option in my .sty file (cmyk or rgb)).   

What kinovar values will be in cmyk?

**Comment by typiconman** [comment]
Based on the converter here: https://www.rapidtables.com/convert/color/rgb-to-cmyk.html
RGB 205,8,3 corresponds to CMYK 0,96,99,20.

**Comment by typiconman** [comment]
I think this issue can be closed.
