### ISSUE TITLE
Change shape and position of hyphenation char

### ISSUE THREAD

**Issue by typiconman** [typiconman/fonts-cu#6]
A user reports:
Символ переноса надо подправить. Он выглядит слишком длинным. Похоже что создатели шрифта делают знак подчеркивания длиной "em". Хотелось бы длину "en" или около того (сравните картинку с моим PDF). Также его поднять бы немного - а то он заметно ниже базовой линии...
![image](https://cloud.githubusercontent.com/assets/5428695/14183649/5e52ebf2-f782-11e5-9c77-8bdcd5b4dc90.png)

**Comment by typiconman** [comment]
@starover77 Please comment.

**Comment by starover77** [comment]
I looked at the character outlines for Ponomar Unicode in FontForge. I agree that the Slavonic hyphen should be narrower (en-width) and rest directly on the baseline. However, the default hyphen should remain as it is, so that it may work correctly with the base Latin character set. I suggest that we use a Stylistic Set for the proper shape of the Slavonic hyphen.

(Also note that the sample image has a half-width hyphen at the end of line 11, but I feel that we need not accommodate this, as it seems to be an unnecessary detail that is font-specific.)

**Comment by pgmmpk** [comment]
Just to make this thread complete. Here is how hyphenation in PonomarUnicode looks presently:

![image](https://cloud.githubusercontent.com/assets/569458/14186328/d20e794e-f74b-11e5-9bbb-6ed68073e446.png)

**Comment by typiconman** [comment]
From Unicode Standard (page 267 of version 8), looks like U+2010 HYPHEN is actually narrower than an En-Dash. And U+002D HYPHEN-MINUS is "average width". 

@starover77 : I agree that U+2010 HYPHEN and U+002D HYPEN MINUS should be hyphens and that U+005F LOW LINE should be the underscore, but sit on the baseline as @pgmmpk suggests, not below it, as we have now.

In TeX, we can specify that U+005F is the hyphenation character. I don't know if that's possible in LibreOffice. I will have to investigate. If its not possible, we may have to create a SS mapping from U+002D to U+005F for LO/AO/MS Office users.

Regarding the half-width hyphen, Unicode does not provide a codepoint for a "narrow low line" (at least I couldn't find one). We could put one in the PUA and creating a mapping to it in the JSTF table. I've been itching to use the JSTF table for something. Although I don't know if software actually supports it.

**Comment by starover77** [comment]
Perhaps I am mistaken, but I see the underscore character being used as a hyphen. I just tried to hyphenate a word in LibreOffice, and I got "благо-дать" as opposed to "благо_дать". Am I doing something wrong? I understand that the Slavonic hyphen is supposed to look like an underscore, but in order to function properly, we shouldn't be using an underscore glyph instead of an actual hyphen glyph. Or is there a language tag (or a Stylistic Set) that substitutes the underscore for a hyphen when hyphenating Slavonic text?

At any rate, I do agree that the character that I see displayed here needs to be nudged upward until is sits precisely on the base line, and be made a bit narrower. However, I am referring to an actual hyphen, not the underscore character (which should be left alone).

**Comment by typiconman** [comment]
@starover77 No, I disagee. I think the underscore should be used for hyphenation in Church Slavonic and the hyphen should be left alone. U+002D is not really a hyphen anyway, but rather a minus sign / hyphen. It shouldn't sit on the baseline. I don't know about U+2010. I think there should be a way to force LibreOffice to use U+005F LOW LINE (underscore) as the hyphenation character. @pgmmpk please comment.

**Comment by starover77** [comment]
OK, I will leave it to your expertise. I haven't been involved with the level of inner mechanics for how the fonts work, so I can't really weigh in on the subject as an informed consultant. I can only remark on what I see visually, and whether it works or not.

**Comment by typiconman** [comment]
We'll have to figure out how hyphenation in LO works first. Regarding the visual look, I think the text posted by @pgmmpk looks a little mechanical (compare with the actual example in the first picture), especially when there are three hyphens in a row (last three lines). It disturbs the eye as very computerized. Perhaps having different-sized hyphens in PUA and letting the software select them via JSTF would solve that problem. Please see the documentation here:
https://www.microsoft.com/typography/otspec/jstf.htm

**Comment by pgmmpk** [comment]
@starover77 My sample was generated by LaTeX, not LibreOffice. In LaTeX I defined U+005F as a symbol used to draw hyphenation marks. I can as easily define any other character, available in the font.

@typiconman Even though changing the shape of font's glyph U+002D will "solve" LibreOffice problem, I am not sure its the right solution. I will leave it to you to decide the mechanics.

About varying hyphen length. Maybe an overkill? On what principles software will decide the hyphen length? Preceding character? Whitespace stretch/shrink level?

Btw, in LaTeX one can control hyphen "badness", so I can probably tune it to avoid placing too many hyphens - avoiding "many hyphens in a row" problem..

What we all seem to agree is this:
* we need it a bit higher
* somewhat shorter (2/3 of the current, perhaps)
* use rounded corners, not sharp ones

**Comment by starover77** [comment]
I am in agreement with Mike. Variable length hyphenation seems like overkill.

In the historical approach to typesetting texts, there has always been a human element to provide a critical eye, and to "massage" the texts to avoid visually unaesthetic problems before printing books. Extra spaces or ligatures were inserted at the discretion of the typographer to resolve issues. However, in these days of computerized typography, the software still cannot adequately provide the human element which is needed for the resolution of such problems. We can write algorithms and other coding to avoid the worst problems, but before anyone actually sends a text file to a professional publisher, it will always need to be carefully examined by a real person to ensure that it is free from unexpected problems that the software cannot anticipate. (For the display of text online, this is not an issue of importance.)

Having written that, the only way that I see to resolve consecutive lines of hyphenation in most software is to add "soft line breaks" and other control characters to force a word to not hyphenate. This would only be done in the final stages of editing when preparing a book to go off to the publisher.

**Comment by KrasnayaPloshchad** [comment]
I have heard XeTeX using HarfBuzz for OpenType layout, so I think using Xe(La)TeX can get better results when you want to get sample or test.

**Comment by typiconman** [comment]
Regarding the use of the hyphenation character in LibreOffice, I have confirmed that LO does not allow a user to choose a different hyphenation character. It is a bug:
https://bugs.documentfoundation.org/show_bug.cgi?id=85731

**Comment by typiconman** [comment]
Fixed.
