### ISSUE TITLE
TeX: strange hyphenation behaviour

### ISSUE THREAD

**Issue by EliseyP** [typiconman/fonts-cu#60]
There is strange problems with hyphenation in footnotes.  

For such code:  
```
\documentclass{article}
\usepackage{polyglossia}
\usepackage{fontspec}
\usepackage{churchslavonic}
\setmainlanguage{churchslavonic}
\newfontfamily\churchslavonicfont[Script=Cyrillic,Ligatures=TeX,HyphenChar=_]{PonomarUnicode.otf}
%\hyphenation{Прис-но-дѣ-вы}
%\lefthyphenmin=2% вверху
%\righthyphenmin=2% внизу
\usepackage{showframe}
\begin{document}

тест\footnote{\hspace{37em} Приснодѣвы.}

тест\footnote{тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест Приснодѣвы.}

тест\footnote{тест . тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест Приснодѣвы.}

тест\footnote{тест . тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест Прис\-но\-дѣ\-вы.}

\fbox{\parbox{3em}{\mbox{} Приснодѣвы }}
\end{document}   
```
I have this output:
![Screenshot_20201106_112845](https://user-images.githubusercontent.com/38728959/98343764-5829a300-2023-11eb-928b-21d2f2215ef1.jpeg)
![Screenshot_20201106_114910](https://user-images.githubusercontent.com/38728959/98345745-1fd79400-2026-11eb-82d6-7ed39831bd9c.jpeg)

Hyphenation work, but not always. Third footnote string looks ugly with unhyphened word "Приснодѣвы".  In fourth footnote string explicit hyphenation not work.   
May be question about general TeX specific and not about churchslavonic - I can't reproduce it with English. Explicit setting \hyphenation, changing \lefthyphenmin \righthyphenmin, \hyphenpenalty, etc. not help.  

**UPD:** with **LuaLaTeX** it work fine. But I need **XeLaTeX**.

**Comment by typiconman** [comment]
Strange. Does the same problem occur with other fonts or is this a Ponomar Unicode issue? @pgmmpk any thoughts?

**Comment by typiconman** [comment]
Since this issue does not seem to be related to the fonts, but rather is a TeX issue, I will close it.
