### ISSUE TITLE
Kerning problems in Ponomar Unicode

### ISSUE THREAD

**Issue by EliseyP** [typiconman/fonts-cu#62]
In LibreOffice kerning for "Тв" pair with **Ponomar Unicode** font looks some strange.  
Top string - **Ponomar Unicode,** down - **Hirmos UCS.**   
Maybe that's what it's meant to be?

![2021-07-08_15-27-44](https://user-images.githubusercontent.com/38728959/124922387-1f066000-e002-11eb-9ce3-59954df10e48.png)

**Comment by starover77** [comment]
Kerning is a principle of modern, western typography. Imposing the principle of kerning onto Church Slavonic fonts seems like a great idea to us in modern times (and I'm sure that a bit of kerning was attempted in some 19th century publications), but its use is quite anachronistic. Take a look at printed editions of Slavonic service books right up to modern times, and you will not see kerning used in many publications. Moreover, if you look at the image of text that you attached (the word "Твоему"), you will see that the individual characters have a more pronounced amount of spacing than modern fonts, which contribute greatly to its legibility.

When Aleksandr Andreev and myself were developing the font, we discussed the issue of kerning at some length, and I seem to recall that we decided not to introduce a significant amount of kerning to tighten the spacing, as it would be an artificial feature. I'm not saying that we didn't apply any kerning at all, but our use of it was subtle and was meant to resolve any truly problematic spacing issues. We didn't set out to make the Ponomar Unicode a "western immitation" font. I think that you are just going to have to get used to loose spacing as a standard feature of the Ponomar Unicode font.

**Comment by EliseyP** [comment]
Thank you, dear Nikita, I understand your idea.  
Not for the dispute - I just look at other pairs with **"Т"** letter in **Ponomar**, such as **"Ти", "Та"** (especially), and think may be for **"Тв"** can be some similar.  
![2021-07-08_18-29-38](https://user-images.githubusercontent.com/38728959/124950036-becfe800-e01a-11eb-91d8-7709fdb839ed.png)

Anyway thank you and Andrey for your job.

**Comment by typiconman** [comment]
It's a bug. Related to #58

**Comment by typiconman** [comment]
Fixed and closed.

**Comment by typiconman** [comment]
Fixed and closed.
