### ISSUE TITLE
Начертание буквы "земля" (U+0437) в PonomarUnicode следует исправить

### ISSUE THREAD

**Issue by Alexk12** [typiconman/fonts-cu#63]
![ponomar-zemlya](https://user-images.githubusercontent.com/16455355/172331891-598e7420-8449-4838-8efc-e0aba3f5160e.png)
Состыковку верхнего и нижнего полуовалов в букве "земля" (U+0437) шрифта PonomarUnicode желательно улучшить и исправить, вероятно (даже очевидно), сделать острой, как это сделано в соответствующем элементе буквы Кси (прописной, U+046E) и в прописной букве "земля".
Шрифт Irmologion (который, как я понял, был прообразом шрифта PonomarUnicode), содержал в этом месте стыковки двух полуовалов ошибку, три небольших криволинейных сегмента, один из которых имел явное искажение. В новом шрифте верхний полуовал, как мне кажется, следует сделать в виде ровной дуги с острой стыковкой с нижним полуовалом.
Поскольку PonomarUnicode похож на шрифт, которым набран церковнославянский текст в Грамматике церковнославянского языка иеромонаха Алипия, думаю, правомерно сравнивать эти шрифты. В шрифте Грамматики, если отсканировать обсуждаемый элемент буквы "земля", стыковка сделана, на мой взгляд, острой.

Кроме того, это уже менее важный момент, но примечательный, в шрифте Грамматики верхний элемент буквы "земля" несколько выступает по высоте за линию строчных букв, то есть он выглядит "выше", чем другие строчные буквы, то есть думаю, что этот момент требует размышлений. Возможно, букву "земля" в шрифте PonomarUnicode также нужно целиком чуть-чуть поднять выше относительно базовой линии.

**Comment by typiconman** [comment]
@starover77 @EliseyP and others, please comment.
По поводу Грамматики вл. Алипия, я бы не слишком доверял ее типографскому набору (как первичному, Джорданвилльскому, так и последующим воспроизведениям). Для нас все таки эталон - издания Синодальной типографии.

**Comment by typiconman** [comment]
Исправил. @Alexk12 посмотрите. Шрифтовой файл можно скачать [отсюда](https://drive.google.com/file/d/15ITiL6qpMmc68Dc5_FJTrrUpq27saYnD/view?usp=sharing).

**Comment by typiconman** [comment]
Fixed and closed.
