### ISSUE TITLE
Superscript kerning problems after LibreOffice update to 7.4 ver.

### ISSUE THREAD

**Issue by EliseyP** [typiconman/fonts-cu#64]
After LibreOffice update to 7.4 ver., there are some problems with ending superscripts kerning.  

![Screenshot_20221013_105536](https://user-images.githubusercontent.com/38728959/195538388-aac59d33-0540-4122-b568-33673e9db838.jpg)

![Screenshot_20221013_105318](https://user-images.githubusercontent.com/38728959/195538463-6f8ec38b-f25d-4ad5-8e78-cf38d3bb0895.jpg)

![Screenshot_20221013_105424](https://user-images.githubusercontent.com/38728959/195538496-1b13c2fe-1557-4719-a347-bc4dfa8f395a.jpg)

And at the same time - if set this word in other place of the string (via new line before it, f.e.) - problem is disappear.

**Comment by typiconman** [comment]
Are we sure this a problem with the font and not a problem with LibreOffice? Does the same problem occur with all of the fonts? Right now I am running version 6.4.7, so cannot verify.

**Comment by EliseyP** [comment]
With `Triodion Unicode` too: 

![Screenshot_20221015_105939](https://user-images.githubusercontent.com/38728959/195976228-ed7eef31-0e9b-46e6-99d7-8f6f8c0df023.jpg)

**Comment by EliseyP** [comment]
It looks like the `7.4` version is still a bit damp. There were problems with running macros from previously installed extensions. I had to roll back to `7.3'.

**Comment by typiconman** [comment]
Do the fonts work OK in 7.3?

**Comment by EliseyP** [comment]
Yes

**Comment by typiconman** [comment]
So I will consider this closed for now.

**Comment by EliseyP** [comment]
No problems after update to LO 7.5.0
