### ISSUE TITLE
Возможные проблемы с переносами в LibreOffice7.6

### ISSUE THREAD

**Issue by EliseyP** [typiconman/fonts-cu#68]
При обновлении LibreOffice до версии 7.6 перестали подключаться переносы для cu-RU. До этого при очередном обновлении переносы подключались автоматически. Переустановка расширения cu-lo.oxt не помогла.    

![Screenshot_20230825_221433](https://github.com/typiconman/fonts-cu/assets/38728959/be2dc7ac-deba-40f3-a350-9292f71a9874)

**Comment by typiconman** [comment]
Ой, у меня еще версия 6.4.7. Попробуйте в 7.5.5, там нормально работает? Вроде бы это последняя версия, которая официально поддерживается. Скорее всего это проблема с самим LO, и надо bug report делать у них.

**Comment by EliseyP** [comment]
В 7.5.5 - все без проблем.

**Comment by EliseyP** [comment]
Проблема решена. Оказывается при обновлении не был установлен пакет `libobasis7.6-ooolinguistic`.
